package cucumber.doc.report;

import java.util.function.Supplier;

import javax.annotation.Nonnull;

import cucumber.doc.report.basic.BasicReport;
import cucumber.doc.report.html.HtmlReport;
import cucumber.doc.report.xml.XmlReport;

/**
 * Defines the different types of report that can be generated by CukeDoc.
 */
public enum Format {
    /** Report as a simple text file */
    BASIC(BasicReport::new),

    /** Report as a XML blob */
    XML(XmlReport::new),

    /** Report as a set of HTML pages */
    HTML(HtmlReport::new);


    private final Supplier<ReportBuilder> constructor;


    Format(@Nonnull Supplier<ReportBuilder> constructor) {
        this.constructor = constructor;
    }


    /**
     * Returns a report builder for this format
     * @return a report builder for this format
     */
    @Nonnull
    public ReportBuilder getReportBuilder() {
        return constructor.get();
    }
}
